/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import GrafosPkg.Grafo;
import javax.swing.JComboBox;

/**
 *
 * @author linda
 */
public class InterGraf extends javax.swing.JFrame {
private final Grafo grafo;
    
    
    /**
     * Creates new form InterGraf
     */
    public InterGraf() {
        grafo= new Grafo("Jutiapa-ElProgreso-AsuncionMita-Atescatempa-Yupiltepeque-Jerez-Moyuta-Comapa-Quesada-Jalpatagua-Pasaco-Zapotitlan-SanJoseAcatempa-Conguaco-ElAdelanto-SantaCatarinaMita-AguaBlanca");
        initComponents();
        LlenarComboBox(CbInicio);
        LlenarComboBox(CbFinal);
        CrearRutas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColor1 = new javax.swing.JColorChooser();
        CbInicio = new javax.swing.JComboBox<>();
        CbFinal = new javax.swing.JComboBox<>();
        jBoton1 = new javax.swing.JButton();
        LbResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);

        CbInicio.setBackground(new java.awt.Color(255, 102, 102));
        CbInicio.setForeground(new java.awt.Color(0, 0, 102));
        CbInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbInicioActionPerformed(evt);
            }
        });

        CbFinal.setBackground(new java.awt.Color(255, 102, 102));
        CbFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBoton1.setBackground(new java.awt.Color(204, 204, 255));
        jBoton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBoton1.setForeground(new java.awt.Color(255, 255, 255));
        jBoton1.setText("Calcular");
        jBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton1ActionPerformed(evt);
            }
        });

        LbResultado.setBackground(new java.awt.Color(255, 153, 255));
        LbResultado.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        LbResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbResultado.setText("Ruta");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Lugar de Inicio:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Lugar de Final:");

        jLabel3.setBackground(new java.awt.Color(153, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ENCUENTRA LA RUTA MÁS CORTAS  ");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 153, 0)));

        jLabel4.setBackground(new java.awt.Color(153, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MUNICIPIOS DE JUTIAPA");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 153, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(CbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CbFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.getAccessibleContext().setAccessibleName("ENCUENTRA LA RUTA MÁS CORTA  ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton1ActionPerformed
        // TODO add your handling code here:
    String inicio = CbInicio.getSelectedItem().toString().trim();
        String fin    = CbFinal.getSelectedItem().toString().trim();
        String respuesta = grafo.encontrarRutaMinimaDijkstra(inicio, fin);
        LbResultado.setText(respuesta);   
    }//GEN-LAST:event_jBoton1ActionPerformed

    private void CbInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbInicioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CbInicioActionPerformed

    private void LlenarComboBox(JComboBox combo){
        combo.removeAllItems();
        combo.addItem("Jutiapa");
        combo.addItem("ElProgreso");
        combo.addItem("AsunciónMita");
        combo.addItem("Atescatempa");
        combo.addItem("Yupiltepeque");
        combo.addItem("Jerez");
        combo.addItem("Moyuta");
        combo.addItem("Comapa");
        combo.addItem("Quesada");
        combo.addItem("Jalpatagua");
        combo.addItem("Pasaco");
        combo.addItem("Zapotitlan");
        combo.addItem("SanJoseAcatempa");
        combo.addItem("Conguaco");
        combo.addItem("ElAdelanto");
        combo.addItem("SantaCatarinaMita");
        combo.addItem("AguaBlanca");
    }
    
    private void CrearRutas(){
        
        grafo.agregarRuta("Jutiapa","Yupiltepeque", 23);
        grafo.agregarRuta("Jutiapa","ElProgreso", 15);
        grafo.agregarRuta("Jutiapa","ElAdelanto", 31);
        grafo.agregarRuta("Jutiapa","Comapa", 43);
        grafo.agregarRuta("Jutiapa","Jalpatagua", 41);
        grafo.agregarRuta("Jutiapa","Quesada", 21);
        
        grafo.agregarRuta("SanJoseAcatempa","Jalpatagua", 35);
        
        grafo.agregarRuta("SantaCatarinaMita","ElProgreso", 20);
        grafo.agregarRuta("SantaCatarinaMita","Jutiapa", 45);
        
        grafo.agregarRuta("AsuncionMita","AguaBlanca", 28);
        grafo.agregarRuta("AsuncionMita","SantaCatarinaMita", 17);
        grafo.agregarRuta("AsuncionMita","Jutiapa",32);
        grafo.agregarRuta("AsuncionMita","Yupiltepeque", 20);
        grafo.agregarRuta("AsuncionMita","Atescatempa", 30);
        grafo.agregarRuta("Quesada","SanJoseAcatempa", 21);
        
       grafo.agregarRuta("AguaBlanca","SantaCatarinaMita", 17);
        
        grafo.agregarRuta("Yupiltepeque","ElAdelanto", 8);
        grafo.agregarRuta("Yupiltepeque","Atescatempa", 15);
        grafo.agregarRuta("Yupiltepeque","Zapotitlan", 10);
        grafo.agregarRuta("Yupiltepeque","Jerez", 16);
        
        grafo.agregarRuta("Jalpatagua","Quesada", 25);
        grafo.agregarRuta("Jalpatagua","Comapa", 17);
        grafo.agregarRuta("Jalpatagua","Conguaco", 21);
        grafo.agregarRuta("Jalpatagua","Moyuta", 22);
        
        grafo.agregarRuta("Atescatempa","Jerez", 12);
        
        grafo.agregarRuta("Jerez","Zapotitlan", 18);
        
        grafo.agregarRuta("Zapotitlan","ElAdelanto", 5);
        grafo.agregarRuta("Zapotitlan","Comapa", 74);
        
       grafo.agregarRuta("Moyuta","Pasaco", 42);
        
        grafo.agregarRuta("ElAdelanto","Comapa", 68);
        
       grafo.agregarRuta("Conguaco","Moyuta", 7);
                

        
        
    }
    /**Set
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*  the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterGraf().setVisible(true);
               
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbFinal;
    private javax.swing.JComboBox<String> CbInicio;
    private javax.swing.JLabel LbResultado;
    private javax.swing.JButton jBoton1;
    private javax.swing.JColorChooser jColor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
